#define _items "optic_Arco","optic_Hamr","optic_ACO_grn","optic_ACO_grn_smg","optic_Holosight","acc_flashlight_smg_01","acc_pointer_IR","optic_DMS","bipod_03_F_blk","optic_Arco_blk_F","optic_DMS_ghex_F","optic_ERCO_blk_F","ItemGPS","ItemMap","Rangefinder","bipod_01_F_snd","U_B_CTRG_3","NVGoggles","acc_flashlight","optic_MRCO","optic_MRD","muzzle_snds_acp","acc_flashlight_pistol","optic_Yorris","muzzle_snds_L","optic_Aco","ItemCompass","ItemWatch","ItemRadio","muzzle_snds_B_snd_F","optic_ERCO_khk_F","optic_Aco_smg","bipod_01_F_khk","optic_Hamr_khk_F","optic_Arco_ghex_F","bipod_02_F_hex","muzzle_snds_93mmg_tan","optic_Holosight_blk_F","muzzle_snds_B_khk_F","bipod_01_F_blk","NVGoggles_OPFOR","muzzle_snds_93mmg","V_CarrierRigKBT_01_light_Olive_F","H_HelmetAggressor_F","O_NVGoggles_grn_F","","optic_Holosight_lush_F"


//#define _silencer                                                                      "muzzle_snds_93mmg_tan","muzzle_snds_L","muzzle_snds_B_khk_F","muzzle_snds_B_snd_F","muzzle_snds_93mmg"



	


//ItemCompass","ItemWatch","ItemRadio","ItemGPS","ItemMap","Rangefinder"






		
	



























